-- Run this once in Supabase Dashboard > SQL Editor.
create table if not exists public.user_progress (
    user_id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null default 'Flounder User',
    bio text not null default 'Welcome to your Flounder profile.',
    total_seconds integer not null default 0 check (total_seconds >= 0),
    active_days jsonb not null default '[]'::jsonb,
    notes integer not null default 0 check (notes >= 0),
    cards integer not null default 0 check (cards >= 0),
    reviews integer not null default 0 check (reviews >= 0),
    achievements jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.user_progress enable row level security;

drop policy if exists "Users can read their own progress" on public.user_progress;
create policy "Users can read their own progress"
    on public.user_progress for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own progress" on public.user_progress;
create policy "Users can insert their own progress"
    on public.user_progress for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own progress" on public.user_progress;
create policy "Users can update their own progress"
    on public.user_progress for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create table if not exists public.analytics_events (
    id bigint generated by default as identity primary key,
    event_type text not null check (event_type in ('visit', 'study_time', 'note_created', 'card_created', 'card_reviewed')),
    user_id uuid references auth.users(id) on delete set null,
    session_id text,
    duration_seconds integer not null default 0 check (duration_seconds >= 0),
    created_at timestamptz not null default now()
);

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at);
create index if not exists analytics_events_session_id_idx on public.analytics_events(session_id);

alter table public.analytics_events enable row level security;

drop policy if exists "Anyone can record analytics events" on public.analytics_events;
create policy "Anyone can record analytics events"
    on public.analytics_events for insert with check (
        (user_id is null or auth.uid() = user_id)
        and (event_type = 'visit' or auth.uid() is not null)
    );

create or replace function public.get_site_analytics()
returns table (
    total_visits bigint,
    unique_visitors bigint,
    active_users bigint,
    study_seconds bigint,
    notes_created bigint,
    cards_created bigint,
    cards_reviewed bigint
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if lower(coalesce(auth.jwt() ->> 'email', '')) <> lower('xsurgent07@gmail.com') then
        raise exception 'Not authorized';
    end if;

    return query
    select
        count(*) filter (where event_type = 'visit'),
        count(distinct session_id) filter (where event_type = 'visit' and session_id is not null),
        count(distinct user_id) filter (where user_id is not null),
        coalesce(sum(duration_seconds) filter (where event_type = 'study_time'), 0),
        count(*) filter (where event_type = 'note_created'),
        count(*) filter (where event_type = 'card_created'),
        count(*) filter (where event_type = 'card_reviewed')
    from public.analytics_events;
end;
$$;

revoke all on function public.get_site_analytics() from public;
grant execute on function public.get_site_analytics() to authenticated;

create table if not exists public.calendar_events (
    id text primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    description text,
    event_date date not null,
    event_type text not null check (event_type in ('exam', 'test', 'assignment', 'study_session')),
    reminder boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists calendar_events_user_id_idx on public.calendar_events(user_id);
create index if not exists calendar_events_date_idx on public.calendar_events(event_date);

alter table public.calendar_events enable row level security;

drop policy if exists "Users can read their own calendar events" on public.calendar_events;
create policy "Users can read their own calendar events"
    on public.calendar_events for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own calendar events" on public.calendar_events;
create policy "Users can insert their own calendar events"
    on public.calendar_events for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update their own calendar events" on public.calendar_events;
create policy "Users can update their own calendar events"
    on public.calendar_events for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own calendar events" on public.calendar_events;
create policy "Users can delete their own calendar events"
    on public.calendar_events for delete using (auth.uid() = user_id);
